device: "cuda"
seed: 20
embed_size: 1024
temp: 0.07
resume: false
# checkpoint: "/mnt/bn/arnold-yy-audiodata/clap_new/wavcaps/WavCaps-master/retrieval/outputs/pretrained/HTSAT-BERT-FT-AudioCaps.pt"
pretrain: true
pretrain_path: '/mnt/bn/arnold-yy-audiodata/clap_new/wavcaps/WavCaps-master/retrieval/outputs/pretrained/HTSAT-BERT-FT-AudioCaps.pt'
embed_regularization: true

dist_args:
  world_size: 8

audio_args:
  sr: 32000
  n_fft: 1024
  hop_length: 320
  f_min: 50
  f_max: 14000
  n_mels: 64
  max_length: 10
  mono: True


audio_encoder_args:
  type: "transformer"
  model: "htsat"
  pretrained: True
  freeze: False


data_args:
  dataset: "llama_data_v2"
  batch_size: 356
  num_workers: 32


text_encoder_args:
  type: 'bert-base-uncased'
  freeze: False
  max_length: 80


optim_args:
  lr: !!float 5e-5
  warmup_steps: 10000
  optimizer_name: "adam"
  betas: [0.9, 0.999]
  eps: !!float 1e-8
  momentum: 0.9
  warmup_epochs: 2


training:
  spec_augmentation: True
  epochs: 50
  clip_grad: 2
  dropout: 0.2
